swagger: '2.0'
info:
  title: jplaceholder service
  version: "0.0.1"
basePath: /
produces:
  - application/json
paths:
  /health:
    get:
      x-workflow: get_health
      responses:
        200:
          description: Feed from API Response
          schema:
            $ref: '#/definitions/HealthResponse'
  /latest_comment:
    get:
      parameters:
        - name: userId
          in: query
          type: integer
          required: false
      x-workflow: get_latest_comment
      responses:
        200:
          description: Latest Comment
          schema:
            $ref: '#/definitions/ObjectResponse'
  /posts:
    get:
      parameters:
        - name: userId
          in: query
          type: integer
          required: false
      x-workflow: get_posts_comments
      responses:
        200:
          description: Posts with comments
          schema:
            $ref: '#/definitions/ObjectResponse'
definitions:
  HealthResponse:
    type: object
  ObjectResponse:
    type: object
